import { NextResponse } from 'next/server';
import { buildModulePrompt } from '@/lib/modulePromptBuilder';
import { createClient } from '@/lib/supabase/server';
import fs from 'fs';
import path from 'path';

export const maxDuration = 120; // 120s timeout para modelos externos

// Obtener rango de nivel según los puntos
function getLevelRange(points: number): number {
  if (points >= 200) return 3;
  if (points >= 100) return 2;
  return 1;
}

// Cargar fallback local de forma segura
function getLocalFallback(moduleId: number): any {
  try {
    const filename = moduleId === 1 ? '01-como-funcionan.json' :
                     moduleId === 2 ? '02-sistemas.json' :
                     moduleId === 3 ? '03-erradicacion.json' : '04-ecosistema.json';
    const filePath = path.join(process.cwd(), 'content', filename);
    const fileContent = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(fileContent);
  } catch (err) {
    console.error("❌ Fallo obteniendo fallback local:", err);
    return null;
  }
}

export async function POST(req: Request) {
  let requestedModuleId = 1;
  try {
    const { moduleId, points } = await req.json();
    requestedModuleId = Number(moduleId || 1);
    const userPoints = Number(points || 0);

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    const userId = user?.id || null;

    // 1. Si no hay sesión (usuario guest), servir el fallback local de inmediato sin gastar API
    if (!userId) {
      console.log(`🌱 Usuario invitado en módulo ${requestedModuleId}. Cargando fallback estático local.`);
      const fallback = getLocalFallback(requestedModuleId);
      return NextResponse.json({ moduleData: fallback, source: 'local_static_guest' });
    }

    // 2. Verificar si ya existe un caché persistente en Supabase para el usuario y módulo
    const { data: cached, error: cacheFetchError } = await supabase
      .from('user_custom_modules')
      .select('*')
      .eq('user_id', userId)
      .eq('module_id', requestedModuleId)
      .maybeSingle();

    if (cacheFetchError) {
      console.warn("⚠️ Error consultando caché de módulos personalizados:", cacheFetchError.message);
    }

    if (cached) {
      const cachedLevel = getLevelRange(cached.points_at_generation);
      const currentLevel = getLevelRange(userPoints);

      // Si el nivel del usuario sigue siendo el mismo en el que se generó, retornamos el caché
      if (cachedLevel === currentLevel) {
        console.log(`⚡ Cargando módulo ${requestedModuleId} desde caché de base de datos (Nivel ${currentLevel}) para usuario ${userId}.`);
        return NextResponse.json({ moduleData: cached.module_data, source: 'database_cache' });
      }
      
      console.log(`🔄 El usuario ${userId} cambió de nivel (${cachedLevel} -> ${currentLevel}). Invalidando caché y regenerando módulo.`);
    }

    // 3. Si no hay caché o cambió el nivel, llamar a Qwen para generar la nueva versión personalizada
    const { systemPrompt, userPrompt } = buildModulePrompt(requestedModuleId, userPoints);
    console.log(`🤖 Generando módulo dinámico ${requestedModuleId} (Nivel ${getLevelRange(userPoints)}) con Qwen para usuario ${userId}.`);

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 95000); // 95 segundos de abort

    const apiRes = await fetch('https://llm-qpkgcaf3gif9hgpv.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.QWEN_API_KEY}`
      },
      signal: controller.signal,
      body: JSON.stringify({
        model: 'qwen-plus',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        stream: false,
        temperature: 0.2
      })
    });
    clearTimeout(timeoutId);

    if (!apiRes.ok) {
      throw new Error(`Qwen API returned status ${apiRes.status}`);
    }

    const data = await apiRes.json();
    let textResponse = data.choices?.[0]?.message?.content || "";

    // Limpieza de tags
    textResponse = textResponse
      .replace(/<\|im_start\|>[\s\S]*?<\|im_end\|>/g, '')
      .replace(/<\|im_start\|>/g, '')
      .replace(/<\|im_end\|>/g, '')
      .replace(/<think>[\s\S]*?<\/think>/g, '')
      .replace(/<\/think>/g, '')
      .replace(/<think>/g, '')
      .replace(/```json/g, '')
      .replace(/```/g, '')
      .trim();

    const jsonMatch = textResponse.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON found in Qwen response");
    }

    const parsedModule = JSON.parse(jsonMatch[0]);

    if (!parsedModule.sections || parsedModule.sections.length === 0) {
      throw new Error("Invalid module structure generated by Qwen");
    }

    // 4. Guardar o actualizar la lección personalizada generada en Supabase (caché persistente)
    const { error: upsertError } = await supabase
      .from('user_custom_modules')
      .upsert({
        user_id: userId,
        module_id: requestedModuleId,
        points_at_generation: userPoints,
        module_data: parsedModule,
        updated_at: new Date().toISOString()
      }, { onConflict: 'user_id,module_id' });

    if (upsertError) {
      console.error("❌ Error guardando lección en caché de Supabase:", upsertError.message);
    } else {
      console.log(`✅ lección personalizada del módulo ${requestedModuleId} guardada en base de datos.`);
    }

    return NextResponse.json({ moduleData: parsedModule, source: 'qwen_generated' });

  } catch (error: any) {
    console.warn(`⚠️ API de Qwen falló para el módulo ${requestedModuleId}. Usando fallback local. Error:`, error.message);
    const fallback = getLocalFallback(requestedModuleId);
    
    if (fallback) {
      return NextResponse.json({ moduleData: fallback, source: 'local_fallback' });
    }
    
    return NextResponse.json({ error: "Fallo completo de generación de módulo." }, { status: 500 });
  }
}
