import { NextResponse } from 'next/server';
import { buildModulePrompt } from '@/lib/modulePromptBuilder';
import { createClient } from '@/lib/supabase/server';
import mockModule1 from '@/../content/01-como-funcionan.json';
import mockModule2 from '@/../content/02-sistemas.json';
import mockModule3 from '@/../content/03-erradicacion.json';
import mockModule4 from '@/../content/04-ecosistema.json';

export const maxDuration = 120; // 120s timeout para modelos externos

// Obtener rango de nivel según los puntos
function getLevelRange(points: number): number {
  if (points >= 200) return 3;
  if (points >= 100) return 2;
  return 1;
}

// Cargar fallback local de forma segura
function getLocalFallback(moduleId: number): any {
  return moduleId === 1 ? mockModule1 :
         moduleId === 2 ? mockModule2 :
         moduleId === 3 ? mockModule3 : mockModule4;
}

export async function POST(req: Request) {
  let requestedModuleId = 1;
  try {
    const { moduleId, points } = await req.json();
    requestedModuleId = Number(moduleId || 1);
    const userPoints = Number(points || 0);

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    const userId = user?.id || null;

    // 1. Si no hay sesión (usuario guest), servir el fallback local de inmediato sin gastar API
    if (!userId) {
      console.log(`🌱 Usuario invitado en módulo ${requestedModuleId}. Cargando fallback estático local.`);
      const fallback = getLocalFallback(requestedModuleId);
      return NextResponse.json({ moduleData: fallback, source: 'local_static_guest' });
    }

    const currentLevel = getLevelRange(userPoints);

    // 2. Verificar el caché de TODOS los módulos para este usuario
    const { data: cachedList, error: cacheFetchError } = await supabase
      .from('user_custom_modules')
      .select('*')
      .eq('user_id', userId);

    if (cacheFetchError) {
      console.warn("⚠️ Error consultando caché de módulos personalizados:", cacheFetchError.message);
    }

    const cachedMap = new Map<number, any>();
    if (cachedList) {
      cachedList.forEach(item => {
        cachedMap.set(item.module_id, item);
      });
    }

    // 3. Determinar qué módulos faltan o están desactualizados para el nivel actual
    const modulesToGenerate: number[] = [];
    for (let m = 1; m <= 4; m++) {
      const cachedModule = cachedMap.get(m);
      const needsGeneration = !cachedModule || getLevelRange(cachedModule.points_at_generation) !== currentLevel;
      if (needsGeneration) {
        modulesToGenerate.push(m);
      }
    }

    // Función auxiliar para generar un módulo individual con Qwen y guardarlo
    const generateAndSaveModule = async (modId: number) => {
      try {
        const { systemPrompt, userPrompt } = buildModulePrompt(modId, userPoints);
        console.log(`🤖 Generando módulo dinámico ${modId} (Nivel ${currentLevel}) con Qwen para usuario ${userId}.`);

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 60000); // 60 segundos por llamada

        const apiRes = await fetch('https://llm-qpkgcaf3gif9hgpv.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${process.env.QWEN_API_KEY}`
          },
          signal: controller.signal,
          body: JSON.stringify({
            model: 'qwen-plus',
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: userPrompt }
            ],
            stream: false,
            temperature: 0.2
          })
        });
        clearTimeout(timeoutId);

        if (!apiRes.ok) {
          throw new Error(`Qwen API returned status ${apiRes.status}`);
        }

        const data = await apiRes.json();
        let textResponse = data.choices?.[0]?.message?.content || "";

        // Limpieza de tags
        textResponse = textResponse
          .replace(/<\|im_start\|>[\s\S]*?<\|im_end\|>/g, '')
          .replace(/<\|im_start\|>/g, '')
          .replace(/<\|im_end\|>/g, '')
          .replace(/<think>[\s\S]*?<\/think>/g, '')
          .replace(/<\/think>/g, '')
          .replace(/<think>/g, '')
          .replace(/```json/g, '')
          .replace(/```/g, '')
          .trim();

        const jsonMatch = textResponse.match(/\{[\s\S]*\}/);
        if (!jsonMatch) {
          throw new Error("No JSON found in Qwen response");
        }

        const parsedModule = JSON.parse(jsonMatch[0]);

        if (!parsedModule.sections || parsedModule.sections.length === 0) {
          throw new Error("Invalid module structure generated by Qwen");
        }

        // Guardar o actualizar la lección personalizada en Supabase
        const { error: upsertError } = await supabase
          .from('user_custom_modules')
          .upsert({
            user_id: userId,
            module_id: modId,
            points_at_generation: userPoints,
            module_data: parsedModule,
            updated_at: new Date().toISOString()
          }, { onConflict: 'user_id,module_id' });

        if (upsertError) {
          console.error(`❌ Error guardando lección ${modId} en caché de Supabase:`, upsertError.message);
        } else {
          console.log(`✅ lección personalizada del módulo ${modId} guardada en base de datos.`);
        }

        return parsedModule;
      } catch (err: any) {
        console.warn(`⚠️ API de Qwen falló para el módulo ${modId}. Usando fallback local. Error:`, err.message);
        const fallback = getLocalFallback(modId);
        if (fallback) {
          return fallback;
        }
        throw err;
      }
    };

    // 4. Si hay módulos pendientes de generación, ejecutarlos en paralelo
    let generatedResultsMap = new Map<number, any>();
    if (modulesToGenerate.length > 0) {
      console.log(`🔄 Módulos que requieren generación/actualización para Nivel ${currentLevel}: ${modulesToGenerate.join(', ')}`);
      const results = await Promise.all(
        modulesToGenerate.map(modId => generateAndSaveModule(modId))
      );
      modulesToGenerate.forEach((modId, index) => {
        generatedResultsMap.set(modId, results[index]);
      });
    }

    // 5. Devolver los datos del módulo solicitado
    let finalModuleData: any = null;
    if (modulesToGenerate.includes(requestedModuleId)) {
      finalModuleData = generatedResultsMap.get(requestedModuleId);
    } else {
      const cached = cachedMap.get(requestedModuleId);
      if (cached) {
        finalModuleData = cached.module_data;
      }
    }

    if (!finalModuleData) {
      console.log(`ℹ️ Módulo solicitado ${requestedModuleId} no encontrado en caché ni en resultados. Usando fallback.`);
      finalModuleData = getLocalFallback(requestedModuleId);
    }

    return NextResponse.json({
      moduleData: finalModuleData,
      source: modulesToGenerate.includes(requestedModuleId) ? 'qwen_generated_batch' : 'database_cache'
    });

  } catch (error: any) {
    console.error(`❌ Error general en generación de módulos. Reintentando con fallback para módulo ${requestedModuleId}:`, error.message);
    const fallback = getLocalFallback(requestedModuleId);
    
    if (fallback) {
      return NextResponse.json({ moduleData: fallback, source: 'local_fallback' });
    }
    
    return NextResponse.json({ error: "Fallo completo de generación de módulo." }, { status: 500 });
  }
}
