import { NextResponse } from 'next/server';
import { buildModulePrompt } from '@/lib/modulePromptBuilder';
import fs from 'fs';
import path from 'path';

export const maxDuration = 120; // 120s timeout para modelos externos

// Cargar fallback local de forma segura
function getLocalFallback(moduleId: number): any {
  try {
    const filename = moduleId === 1 ? '01-como-funcionan.json' :
                     moduleId === 2 ? '02-sistemas.json' :
                     moduleId === 3 ? '03-erradicacion.json' : '04-ecosistema.json';
    const filePath = path.join(process.cwd(), 'content', filename);
    const fileContent = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(fileContent);
  } catch (err) {
    console.error("❌ Fallo obteniendo fallback local:", err);
    return null;
  }
}

export async function POST(req: Request) {
  let requestedModuleId = 1;
  try {
    const { moduleId, points } = await req.json();
    requestedModuleId = Number(moduleId || 1);
    const userPoints = Number(points || 0);

    const { systemPrompt, userPrompt } = buildModulePrompt(requestedModuleId, userPoints);

    console.log(`🤖 Generando módulo dinámico ${requestedModuleId} para usuario con ${userPoints} puntos (Qwen)`);

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 95000); // 95 segundos de abort

    const apiRes = await fetch('https://llm-qpkgcaf3gif9hgpv.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.QWEN_API_KEY}`
      },
      signal: controller.signal,
      body: JSON.stringify({
        model: 'qwen-plus',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        stream: false,
        temperature: 0.2
      })
    });
    clearTimeout(timeoutId);

    if (!apiRes.ok) {
      throw new Error(`Qwen API returned status ${apiRes.status}`);
    }

    const data = await apiRes.json();
    let textResponse = data.choices?.[0]?.message?.content || "";

    // Limpiar posibles bloques im_start/im_end o markdown
    textResponse = textResponse
      .replace(/<\|im_start\|>[\s\S]*?<\|im_end\|>/g, '')
      .replace(/<\|im_start\|>/g, '')
      .replace(/<\|im_end\|>/g, '')
      .replace(/<think>[\s\S]*?<\/think>/g, '')
      .replace(/<\/think>/g, '')
      .replace(/<think>/g, '')
      .replace(/```json/g, '')
      .replace(/```/g, '')
      .trim();

    // Buscar el primer objeto JSON válido en la respuesta
    const jsonMatch = textResponse.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON found in Qwen response");
    }

    const parsedModule = JSON.parse(jsonMatch[0]);

    if (!parsedModule.sections || parsedModule.sections.length === 0) {
      throw new Error("Invalid module structure generated by Qwen");
    }

    console.log(`✅ Módulo dinámico ${requestedModuleId} generado con éxito por Qwen.`);
    return NextResponse.json({ moduleData: parsedModule, source: 'qwen' });

  } catch (error: any) {
    console.warn(`⚠️ API de Qwen falló o dio timeout para el módulo ${requestedModuleId}. Usando fallback local. Error:`, error.message);
    const fallback = getLocalFallback(requestedModuleId);
    
    if (fallback) {
      return NextResponse.json({ moduleData: fallback, source: 'local_fallback' });
    }
    
    return NextResponse.json({ error: "Fallo completo de generación de módulo." }, { status: 500 });
  }
}
